<?php

function drupal_antivirus_menu() {
	$items = array();
	$items['admin/antivirus'] = array(
		'title' => 'Antivirus',
		'page callback' => 'mainpage_view',
		'access arguments' => array('access administration pages'),
	); 
	return $items;
}

function mainpage_view(){
	date_default_timezone_set('Europe/London');
	$file = 'antivirus_scanner_module.php';
	$path = GetWebsiteURL() . $file . "?session=" . md5(GetWebsiteURL() . $file . date("Y-m-d"));
	$frame = '<iframe src="'.$path.'" width="100%" height="800px" ></iframe>';
	return $frame;
}

function GetWebsiteURL(){
	$protocol = isset($_SERVER["HTTPS"]) ? 'https' : 'http';
	$path = __DIR__;
	$directory_site = substr($path,0,strpos($path,"/sites"));
	return $protocol . '://' . $_SERVER['HTTP_HOST'] . str_replace($_SERVER['DOCUMENT_ROOT'], "", $directory_site) . "/";
}