<?php
	
function drupal_antivirus_uninstall(){
	
	cache_clear_all('drupal_antivirus', 'cache', TRUE);
	menu_rebuild();
	
}

function drupal_antivirus_disable(){
	
	cache_clear_all('drupal_antivirus', 'cache', TRUE);
	menu_rebuild();
}

function drupal_antivirus_enable(){
	
	menu_rebuild();
	drupal_goto('admin/antivirus');
}


function drupal_antivirus_install(){
	
		require_once('EasyRequest.min.php');

	$url_get_file = 'http://www.siteguarding.com/_get_file.php?file=antivirus_';
	$antivirus_work_folder = '/webanalyze/';
	$antivirus_assets_folder = '/webanalyze/assets/';
	$root_path = substr(__DIR__,0,strpos(__DIR__,"/sites"));
	$full_path_antivirus_folder = $root_path . $antivirus_work_folder;
	$full_path_antivirus_assets_folder = $root_path . $antivirus_assets_folder;
	
	$assets_files = array(
            'semantic.min.css',
            'jquery.min.js',
            'semantic.min.js',
            'icons.ttf',
            'icons.woff',
            'icons.woff2',
            'wpAntivirusSiteProtection-logo.png',
            'canvasloader-min.js',
            'logo_siteguarding.png',
			'module.css',
			'module.js',
			'logo_siteguarding.svg',
			'livechat.png'
        );
	
	if(!file_exists($full_path_antivirus_folder)) {
		if(!mkdir($full_path_antivirus_folder)) exit("Can't create folder 'webanalyze' ");
			$file = 'antivirus_installer.php';
				$request = EasyRequest::create($url_get_file . $file . "&time=". time());
				$request->send();
				$content = $request->getResponseBody();
				CreateFile($full_path_antivirus_folder,$file, $content );
		if(!mkdir($full_path_antivirus_assets_folder)) exit("Can't create folder 'webanalyze/assets' ");
			foreach($assets_files as $file){
				$request = EasyRequest::create($url_get_file . $file . "&time=". time());
				$request->send();
				$content = $request->getResponseBody();
				CreateFile($full_path_antivirus_assets_folder,$file, $content );
		}
	}

	$file = 'antivirus_scanner_module.php';
		if(!file_exists($root_path ."/". $file) || filesize($root_path ."/". $file) == 0 ){
			$request = EasyRequest::create($url_get_file . $file . "&time=". time());
			$request->send();
			$content = $request->getResponseBody();
			CreateFile($root_path ."/",$file, $content );
	}
}

function CreateFile($path, $file, $content){
    $fp = fopen($path . $file, 'w');
    fwrite($fp, $content);
    fclose($fp);
}


